@BiDegree.Api_HostAddress = https://localhost:44342



GET {{BiDegree.Api_HostAddress}}/api/GetFile

###

GET {{BiDegree.Api_HostAddress}}/api/picture/list

###

GET {{BiDegree.Api_HostAddress}}/api/picture/list

###
